### ISSUE TITLE
Show the user information if they are currently in liquidation liveness period

### ISSUE THREAD

**Issue by chrismaree** [UMAprotocol/emp-tools#104]
right now there is no way to see if you are liquidated other than your collateral & tokens will be lower. there should be feedback to the user showing the liquidation state.

**Comment by nicholaspai** [comment]
I'm building a "Your Liquidations" feature that we can add to the ManagePositions page, and we'll display a bold alert on the main GeneralInfo page if a sponsor is currently being liquidated.

Your Liquidations will display current and past liquidations.

**Comment by nicholaspai** [comment]
Closed by #108
