### ISSUE TITLE
You can unselelect both tabs on the position info & actions modal

### ISSUE THREAD

**Issue by mrice32** [UMAprotocol/emp-tools#150]
<img width="551" alt="Screen Shot 2020-09-07 at 10 42 06 AM" src="https://user-images.githubusercontent.com/11791551/92398610-e7373f00-f0f6-11ea-8aaf-778d2fa9c1d1.png">

**Comment by nicholaspai** [comment]
This also applies for the Liquidity Mining | Yield Dollar section
