### ISSUE TITLE
WalletConnect txs fail on frontend

### ISSUE THREAD

**Issue by rhlsthrm** [UMAprotocol/emp-tools#191]
When I try to do anything I get this error: 
`The method eth_sendTransaction does not exist/is not available`

This could be due to outdated packages?

**Comment by rhlsthrm** [comment]
I spoke to some of the WalletConnect team about this issue, they said it's most likely due to the Infura key not being valid.

**Comment by chrismaree** [comment]
Thanks for finding this and reporting the bug! I've upgraded onboard.js which seemed to fix it in my testing. Please let me know if this has not resolved your issues :)

**Comment by rhlsthrm** [comment]
Just tested it, it works! Thank you for the fix!
