### ISSUE TITLE
429, too many requests to Coingecko after unlocking wallet

### ISSUE THREAD

**Issue by akhanubis** [UMAprotocol/emp-tools#222]
The page still works, except for the YUSD YIELD liq mining section which I guess uses prices from coingecko.

![image](https://user-images.githubusercontent.com/2922430/112731388-acbbb500-8f15-11eb-92e1-4569a2f360b2.png)

It's doing 140 req to coingecko (2 per fetch because of OPTIONS), so some of them work and the rest trigger 429. I tried waiting for the ban to expire and then trying again to discard me having opened multiple tabs or something, but the issue persists.

It is also querying the same address multiple times which contributes to there being to many requests.

**Comment by daywiss** [comment]
Thanks for reporting this, this was happening during development as well. Since the list of EMPs has grown, we are making a lot more requests to external apis.
