### ISSUE TITLE
Footer shows up two times

### ISSUE THREAD

**Issue by chrismaree** [UMAprotocol/emp-tools#51]
At the same time, improving the footer would be great.
![image](https://user-images.githubusercontent.com/12886084/88283474-b8ead500-cceb-11ea-9981-678f9f1df58b.png)

**Comment by nicholaspai** [comment]
I am unable to reproduce this bug can you share more details?

**Comment by chrismaree** [comment]
it only is present on `master`, not `develop`. If you go to http://tools.umaproject.org/ you'll see the issue there in production

**Comment by chrismaree** [comment]
> I am unable to reproduce this bug can you share more details?

it only is present on `master`, not `develop`. If you go to http://tools.umaproject.org/ you'll see the issue there in production

**Comment by nicholaspai** [comment]
> > I am unable to reproduce this bug can you share more details?
> 
> it only is present on `master`, not `develop`. If you go to http://tools.umaproject.org/ you'll see the issue there in production

Gotta be a merge conflict

**Comment by nicholaspai** [comment]
Closed by #52
