### ISSUE TITLE
Get rid of null checks in rendering logic

### ISSUE THREAD

**Issue by mrice32** [UMAprotocol/emp-tools#68]
I was thinking about how we might avoid the null checks in normal logic throughout the dapp. In the past I've generally used loading guards to block off the logic until the data is all non-null.

However, @adrianmcli mentioned is that the user shouldn't have to connect their wallet to view read-only info. I like that philosophy a lot, but there are a few issues with it in this dapp right now:
- Many of these pages are't viewable until the EMP-selector has data, so these pages can't be seen without connecting anyway.
- Since we're unable to load much data on the page before connecting, the data that the user can see (at least on many pages) is somewhat useless.

I think we should:
- Put loading guards at the top of most of the pages (at least the ones that require an EMP) to block the render function until _all_ required data is loaded. This would look like:

```js
if (someDataFromContainer === null || otherDataFromContainer === null || ... ) {
  return (
    <LoadingJSX />
  );
}
```

- Figure out how to connect a read-only provider that would allow us to load blockchain data without the user connecting a wallet.

Thoughts @nicholaspai @chrismaree @adrianmcli?

**Comment by nicholaspai** [comment]
I totally agree that the null checks are making the code very unreadable. I think this is a great idea: we will check for `null` or other invalid edge cases up front and then assume from there on that the data is in the valid form. I'll start implementing this on #55 for the Create/Withdraw/Redeem/Deposit features
