### ISSUE TITLE
Hide EMP info if no contract selected

### ISSUE THREAD

**Issue by chrismaree** [UMAprotocol/emp-tools#8]
If the user has not chosen an EMP contract they should not see the EMP info:
![image](https://user-images.githubusercontent.com/12886084/86343125-d41c7480-bc58-11ea-9ff5-664ca550bf96.png)

**Comment by adrianmcli** [comment]
I actually went out of my way to make this the case. It would be much easier to build this dapp if we just hid everything until they were connected.

It's usually beneficial to let the user see what kind of info your dapp does before requiring them to connect.

From the Rimble UX guide:

> Don't... Block the user from exploring your dapp until they've connected, if you don't need to be connected to browse

https://rimble.consensys.design/guides/ux/connect-a-wallet-conditions

**Comment by nicholaspai** [comment]
+1 to Adrian's point on emphasizing explorability. We could even display a helpful graphic visually explaining how the different EMP actions work

**Comment by adrianmcli** [comment]
As much as I want explorability, it does require a lot more in terms of maintainance and work lol. Thanks for the +1 @nicholaspai

**Comment by nicholaspai** [comment]
I think we can enable explorability of EMP stats WITHOUT having to sign in by using the subgraph data.
